FROM golang:1.25-alpine
RUN apk add --no-cache git bash
WORKDIR /app
RUN go install github.com/air-verse/air@latest
COPY go.mod go.sum ./
RUN go mod download
RUN mkdir -p tmp
EXPOSE 8081
CMD ["air", "-c", ".air.toml"]